name: ihh_project_chatbot
description: "Toplu Mesaj Gönderim Arayüzü"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.1.6
  http: ^1.2.0
  excel: ^4.0.6
  shared_preferences: 2.5.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  windows: true
  web: true
  macos: true
  image_path: "assets/images/ihh_logo.png"
